### ISSUE TITLE
Exception seen on close_session

### ISSUE THREAD

**Issue by einarnn** [CiscoDevNet/ncc#9]
Sometimes this exception is seen when ncclient's `close_session` is called:

```
./ncc.py --host=10.10.6.2 -u sdn -p sdn --port 830 --get-oper --xpath '/IF-MIB/ifTable/ifEntry[ifPhysAddress="7c:95:f3:bd:2b:64"]' | grep OutOct
Exception in thread session (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/home/grapevine/NETCONF/ncc/env/local/lib/python2.7/site-packages/ncclient/transport/ssh.py", line 575, in run
  File "/home/grapevine/NETCONF/ncc/env/local/lib/python2.7/site-packages/ncclient/transport/ssh.py", line 312, in close
  File "/home/grapevine/NETCONF/ncc/env/local/lib/python2.7/site-packages/paramiko/transport.py", line 651, in close
  File "/home/grapevine/NETCONF/ncc/env/local/lib/python2.7/site-packages/paramiko/transport.py", line 1546, in stop_thread
  File "/usr/lib/python2.7/threading.py", line 960, in join
  File "/usr/lib/python2.7/threading.py", line 363, in wait
<type 'exceptions.ValueError'>: list.remove(x): x not in list
```

Should suppress this.

**Comment by einarnn** [comment]
Addressed in #11 , but going to open an issue to track whether that exception results in a possible file descriptor leak at remote end with ConfD-based implementations due to improper session closure.

**Comment by aradford123** [comment]
Not as easy as i thought to catch..
<type 'exceptions.ValueError'>: list.remove(x): x not in list
That is different to Exception ValueError

**Comment by einarnn** [comment]
Probably addressed by recent updates to main `ncclient` library. No active issue known here.
